// Mock data for development and testing
import { Article } from '@/types';

export const mockArticles: Article[] = [
  {
    _id: '1',
    title: 'Cyprus Real Estate Market Overview 2025',
    titleHe: 'סקירת שוק הנדל"ן בקפריסין 2025',
    content: 'The Cyprus real estate market continues to show strong growth...',
    contentHe: 'שוק הנדל"ן בקפריסין ממשיך להראות צמיחה חזקה...',
    category: 'market-analysis',
    categoryHe: 'ניתוח שוק',
    slug: 'cyprus-real-estate-market-overview-2025',
    excerpt: 'An in-depth analysis of the Cyprus property market trends',
    excerptHe: 'ניתוח מעמיק של מגמות שוק הנדל"ן בקפריסין',
    readTime: 8,
    createdAt: new Date('2025-01-15').toISOString(),
    published: true,
    status: 'approved',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
  },
  {
    _id: '2',
    title: 'Tax Benefits for Israeli Investors in Cyprus',
    titleHe: 'הטבות מס למשקיעים ישראלים בקפריסין',
    content:
      'Cyprus offers significant tax advantages for international investors...',
    contentHe: 'קפריסין מציעה יתרונות מס משמעותיים למשקיעים בינלאומיים...',
    category: 'legal',
    categoryHe: 'משפטי',
    slug: 'tax-benefits-israeli-investors-cyprus',
    excerpt: 'Learn about the tax advantages available to Israeli investors',
    excerptHe: 'למדו על יתרונות המס הזמינים למשקיעים ישראלים',
    readTime: 6,
    createdAt: new Date('2025-01-20').toISOString(),
    published: true,
    status: 'approved',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c',
  },
  {
    _id: '3',
    title: 'Investment Guide: Limassol Marina District',
    titleHe: 'מדריך השקעה: אזור המרינה בלימסול',
    content:
      'The Limassol Marina area has become one of the most sought-after...',
    contentHe: 'אזור המרינה בלימסול הפך לאחד המבוקשים ביותר...',
    category: 'investment-guide',
    categoryHe: 'מדריך השקעה',
    slug: 'investment-guide-limassol-marina',
    excerpt: 'Why Limassol Marina is a top investment destination',
    excerptHe: 'מדוע מרינת לימסול היא יעד השקעה מוביל',
    readTime: 10,
    createdAt: new Date('2025-01-25').toISOString(),
    published: true,
    status: 'approved',
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716',
  },
];

export const mockProperties = [
  {
    _id: '1',
    title: 'Luxury Villa in Limassol',
    titleHe: 'וילת יוקרה בלימסול',
    price: 850000,
    priceILS: 3187500,
    location: {
      city: 'Limassol',
      cityHe: 'לימסול',
      area: 'Marina',
      areaHe: 'מרינה',
      coordinates: [34.707817, 33.022469],
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      sqm: 280,
      pool: true,
      seaview: true,
      parking: true,
    },
    description: 'Stunning modern villa with panoramic sea views',
    descriptionHe: 'וילה מודרנית מדהימה עם נוף פנורמי לים',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
    ],
    roi: {
      rentalYield: 5.8,
      appreciation: 8.2,
    },
    propertyType: 'villa',
    propertyTypeHe: 'וילה',
    slug: 'luxury-villa-limassol-marina',
    createdAt: new Date('2025-01-10').toISOString(),
    published: true,
  },
];
